include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        f"{OUTDIR}/Report/fastp_multiqc.html",
        f"{OUTDIR}Report/Align_multiqc.html",
        expand("{o}/Report/Centrifuge/{s}.kreport.tsv",s=SAMPLE),
        expand("{o}/Report/Bracken/{s}.bracken.tsv",s=SAMPLE),
        expand("{o}/Report/Krona/{s}.html",s=SAMPLE),
        expand("VFDB/{s}.tsv",s=SAMPLE),
        expand("{o}/RGI/{s}.txt",s=SAMPLE),

##### Modules #####
include: "rules/trim.smk"
# include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/classify.smk"
include: "rules/qc.smk"
include: "rules/assemble.smk"
